# students marks analysis using numpy




#import numy as np


In [1]:
import numpy as np

# creating student marks array

In [3]:
marks=np.array([78,98,65,89,95,75,85])
print("student marks:")
print(marks)

student marks:
[78 98 65 89 95 75 85]


# find total marks of a student

In [4]:
total=np.sum(marks)
print("total marks:",total)

total marks: 585


# finding average marks of a student


In [5]:
average=np.mean(marks)
print("average marks:",average)

average marks: 83.57142857142857


finding highest and lowest marks of a student

In [6]:
highest=np.max(marks)
lowest=np.min(marks)
print("highest marks",highest)
print("lowest marks",lowest)




highest marks 98
lowest marks 65


# sort marks


In [9]:
sorted_marks=np.sort(marks)
print("sorted marks:")
print (sorted_marks)


sorted marks:
[65 75 78 85 89 95 98]


# find passed students

In [10]:
passed_students=marks[marks>=70]
print("passed students marks':")
print(passed_students)


passed students marks':
[78 98 89 95 75 85]


#conclusion "this mini project analyses student marks using numpy functions such as sum, mean, maximum and minimum,sorting,and filtering passed out students."